name: news_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_screenutil: ^5.9.3
  http: ^1.3.0
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.2
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  meta: ^1.15.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
flutter_native_splash:
  background_image: assets/images/news.jpeg # الصورة ستملأ الشاشة بالكامل
  android: true
  ios: true
  fullscreen: true
